# Generated by Django 6.0.4 on 2026-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_sr', 'Site Register'), ('ss_entry', 'Supply'), ('si_entry', 'Supply and Installation'), ('ee_entry', 'Execution'), ('financial', 'Financial'), ('loa_unassigned', 'LOA Unassigned')], max_length=20),
        ),
    ]
