# Generated by Django 6.0.4 on 2026-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sheet_url', models.URLField(max_length=500)),
                ('sheet_id', models.CharField(blank=True, editable=False, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site GSheet',
                'verbose_name_plural': 'Site GSheets',
                'ordering': ['name'],
            },
        ),
    ]
