# Generated by Django 6.0.4 on 2026-04-24 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0009_drop_workbill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_number', models.PositiveIntegerField(help_text='User-entered MB number')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mb_records', to='works.work')),
            ],
            options={
                'ordering': ['work_id', 'mb_number'],
                'unique_together': {('work', 'mb_number')},
            },
        ),
        migrations.CreateModel(
            name='MBItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Qty of this item billed in this line')),
                ('prior_percentage', models.FloatField(default=0, help_text='Cumulative % already paid before this MB')),
                ('current_percentage', models.FloatField(help_text='Cumulative % after this MB')),
                ('amount', models.FloatField(default=0, help_text='Auto: qty × rate × (current - prior) / 100')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mb_items', to='works.workitem')),
                ('mb_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mb_details.mbrecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
