# Generated by Django 6.0.4 on 2026-04-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbrecord',
            name='mb_number',
            field=models.CharField(help_text='User-entered MB number/reference (free text)', max_length=500),
        ),
    ]
