# Generated by Django 6.0.4 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_details', '0002_alter_mbrecord_mb_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbrecord',
            name='measurement_date',
            field=models.DateField(blank=True, help_text='Date of measurement as recorded in the MB', null=True),
        ),
    ]
