# Generated by Django 6.0.4 on 2026-08-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0016_workextension_add_ld_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drive Sync Settings',
                'verbose_name_plural': 'Drive Sync Settings',
            },
        ),
        migrations.CreateModel(
            name='DriveFolderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workbills_folder_url', models.URLField(blank=True, default='', max_length=500)),
                ('workbills_folder_id', models.CharField(blank=True, editable=False, max_length=200)),
                ('crn_folder_url', models.URLField(blank=True, default='', max_length=500)),
                ('crn_folder_id', models.CharField(blank=True, editable=False, max_length=200)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_folder_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drive Folder Link',
                'verbose_name_plural': 'Drive Folder Links',
            },
        ),
        migrations.CreateModel(
            name='SyncedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=200)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('modified_time', models.CharField(blank=True, default='', max_length=100)),
                ('kind', models.CharField(choices=[('bill', 'Bill'), ('receipt', 'Receipt (CRN)')], max_length=20)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('needs_review', 'Needs Review'), ('error', 'Error')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('folder_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_files', to='drive_sync.drivefolderlink')),
                ('matched_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work')),
            ],
            options={
                'verbose_name': 'Synced File',
                'verbose_name_plural': 'Synced Files',
                'ordering': ['-synced_at'],
                'unique_together': {('folder_link', 'drive_file_id')},
            },
        ),
    ]
