# Generated by Django 6.0.4 on 2026-05-18 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0015_snapshot_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRegisterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('sse', 'SSE'), ('contractor', 'Contractor')], max_length=20)),
                ('message_text', models.TextField(blank=True)),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteRegisterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_file_id', models.TextField()),
                ('tg_file_unique_id', models.TextField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('pdf', 'PDF')], max_length=20)),
                ('archive_group_message_id', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='site_register.siteregistermessage')),
            ],
        ),
        migrations.CreateModel(
            name='SiteRegisterThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by_role', models.CharField(choices=[('sse', 'SSE'), ('contractor', 'Contractor')], max_length=20)),
                ('category', models.CharField(choices=[('order', 'SSE Order'), ('progress', 'Progress Update'), ('hindrance', 'Hindrance'), ('inspection_request', 'Inspection Request'), ('document_submission', 'Document Submission'), ('general_remark', 'General Remark')], max_length=30)),
                ('initial_text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20)),
                ('tg_order_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_threads_created', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_threads', to='works.work')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_threads', to='works.workitem')),
            ],
        ),
        migrations.AddField(
            model_name='siteregistermessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='site_register.siteregisterthread'),
        ),
        migrations.CreateModel(
            name='TelegramLinkOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkContractorTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sse', 'SSE'), ('contractor', 'Contractor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_mappings', to='site_register.telegramuserlink')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_parties', to='works.work')),
            ],
            options={
                'unique_together': {('work', 'telegram_link')},
            },
        ),
    ]
