# Generated by Django 6.0.4 on 2026-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_register', '0002_botsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlinkotp',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramlinkotp',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
