# Generated by Django 6.0.4 on 2026-05-18 11:24

from django.db import migrations, models


def migrate_roles_forward(apps, schema_editor):
    WCT   = apps.get_model('site_register', 'WorkContractorTelegram')
    SRT   = apps.get_model('site_register', 'SiteRegisterThread')
    SRM   = apps.get_model('site_register', 'SiteRegisterMessage')
    WCT.objects.filter(role='sse').update(role='site_supervisor')
    WCT.objects.filter(role='contractor').update(role='site_supervisor')
    SRT.objects.filter(initiated_by_role='sse').update(initiated_by_role='rly_official')
    SRT.objects.filter(initiated_by_role='contractor').update(initiated_by_role='site_supervisor')
    SRM.objects.filter(sender_role='sse').update(sender_role='rly_official')
    SRM.objects.filter(sender_role='contractor').update(sender_role='site_supervisor')


class Migration(migrations.Migration):

    dependencies = [
        ('site_register', '0003_otp_6digit_expiry'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_forward, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='siteregistermessage',
            name='sender_role',
            field=models.CharField(choices=[('rly_official', 'Rly Official'), ('site_supervisor', 'Site Supervisor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='siteregisterthread',
            name='category',
            field=models.CharField(choices=[('order', 'Rly Official Order'), ('progress', 'Progress Update'), ('hindrance', 'Hindrance'), ('inspection_request', 'Inspection Request'), ('document_submission', 'Document Submission'), ('general_remark', 'General Remark')], max_length=30),
        ),
        migrations.AlterField(
            model_name='siteregisterthread',
            name='initiated_by_role',
            field=models.CharField(choices=[('rly_official', 'Rly Official'), ('site_supervisor', 'Site Supervisor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workcontractortelegram',
            name='role',
            field=models.CharField(choices=[('site_supervisor', 'Site Supervisor')], max_length=20),
        ),
    ]
