# Generated by Django 6.0.4 on 2026-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_register', '0005_supervisor_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuserlink',
            name='onboard_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telegramuserlink',
            name='onboard_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='telegramuserlink',
            name='onboard_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
