# Generated by Django 6.0.4 on 2026-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_register', '0007_rly_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteregisterthread',
            name='work_serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
