# Generated by Django 6.0.4 on 2026-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_register', '0008_work_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteregisterattachment',
            name='att_serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
