# Generated by Django 6.0.4 on 2026-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_register', '0010_thread_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteregisterthread',
            name='assigned_consignee_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteregisterthread',
            name='assigned_consignee_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
