# Generated by Django 6.0.4 on 2026-06-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0015_snapshot_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=200)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('loa_number', models.CharField(blank=True, max_length=200)),
                ('agreement_number', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='works.work')),
            ],
            options={
                'ordering': ['bill_date', 'bill_number'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=50)),
                ('item_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('agreement_rate', models.FloatField(default=0)),
                ('current_agmt_qty', models.FloatField(default=0)),
                ('amt_total', models.FloatField(default=0)),
                ('bill_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial_progress.billrecord')),
            ],
            options={
                'ordering': ['schedule_name', 'item_number'],
            },
        ),
    ]
