# Generated by Django 6.0.4 on 2026-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='qty_upto_date',
            field=models.FloatField(default=0),
        ),
    ]
