# Generated by Django 6.0.4 on 2026-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_progress', '0002_add_qty_upto_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='total_amount_override',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
