# Generated by Django 6.0.4 on 2026-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_progress', '0003_add_total_amount_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='original_agmt_qty',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
