# Generated by Django 6.0.4 on 2026-04-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loa_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tender_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_agreement', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_address', models.TextField(blank=True, null=True)),
                ('date_of_completion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_rate_rs', models.FloatField(blank=True, null=True)),
                ('unit_rate_below', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='works.work')),
            ],
        ),
    ]
