# Generated by Django 6.0.4 on 2026-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='challan_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='supplied_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='technical_specification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='udm_entry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
