# Generated by Django 6.0.4 on 2026-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_workitem_updated_at_workitem_updated_by_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='consignee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
