# Generated by Django 6.0.4 on 2026-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_entry_type_location_remarks_executed_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitementry',
            name='date_of_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='deviations_deficiencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='electrical_parameters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='inspection_status',
            field=models.CharField(blank=True, default='accepted', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='item_serial_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='manufacturer_oem',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='marking_on_material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='mechanical_parameters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='other_parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='sample_test_officer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='specification_drawing_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='total_offered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='total_passed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='total_rejected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='trademark_batch_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='visual_condition',
            field=models.CharField(blank=True, default='OK', max_length=50, null=True),
        ),
    ]
