# Generated by Django 6.0.4 on 2026-05-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_drop_workbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name_of_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
