# Generated by Django 6.0.4 on 2026-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_workitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='category',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('supply_installation', 'Supply & Installation'), ('execution', 'Execution')], max_length=100, null=True),
        ),
    ]
