# Generated by Django 6.0.4 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_alter_workitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='updated_by_designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='workitementry',
            name='submitted_by_designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
