# Generated by Django 6.0.4 on 2026-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_snapshot_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workextension',
            name='ld_amount',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workextension',
            name='ld_type',
            field=models.CharField(choices=[('without_ld', 'Without LD'), ('with_ld', 'With LD')], default='without_ld', max_length=20),
        ),
    ]
