# Generated by Django 6.0.4 on 2026-05-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('consignee', 'Consignee'), ('admin', 'Admin'), ('sse', 'SSE'), ('contractor', 'Contractor')], default='consignee', max_length=20),
        ),
    ]
