# Generated by Django 6.0.4 on 2026-07-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_mobile_number_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pf_number',
        ),
    ]
