# Generated by Django 6.0.4 on 2026-07-21 11:24

from django.db import migrations, models


def _flag_admin_as_super_admin(apps, schema_editor):
    """
    Replaces the old hardcoded `username == 'admin'` super-admin check with a
    real DB flag. The 'admin' account previously had no UserProfile row at all
    (created via createsuperuser) — create one if missing so the flag has
    somewhere to live, and set it on any existing profile too.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    try:
        admin_user = User.objects.get(username='admin')
    except User.DoesNotExist:
        return
    profile, _created = UserProfile.objects.get_or_create(
        user=admin_user,
        defaults={
            'designation': 'Super Admin',
            'is_approved': True,
            'role': 'admin',
        },
    )
    if not profile.is_super_admin:
        profile.is_super_admin = True
        profile.save(update_fields=['is_super_admin'])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_pf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_flag_admin_as_super_admin, _noop_reverse),
    ]
